# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Site settings
title: "Third Workshop on Fairness and Ethics Towards Transparent AI: Facing the Challenge Through Model Debiasing (FAILED)"
subtitle: "Workshop at ECCV 2026, Malmö, Sweden"
description: "Workshop at the European Conference on Computer Vision 2026"
keywords: "Fairness, Bias, Debiasing, Computer Vision, ECCV 2026, Transparent AI"

repo: "https://github.com/3rd-failed-workshop-ECCV-2026/3rd-failed-workshop-ECCV-2026"

url: "https://3rd-failed-workshop-ECCV-2026.github.io"
baseurl: "/3rd-failed-workshop-ECCV-2026"

google-analytics-id:

defaults:
  - scope:
      path: ""
    values:
      layout: default

markdown: kramdown
